[project]
name = "caden"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.8.5",
    "fastapi>=0.136.3",
    "matplotlib>=3.10.9",
    "python-multipart>=0.0.30",
    "uvicorn>=0.48.0",
]

[tool.pyrefly]
search_path = ["./"]

[tool.ruff]
src = ["."]
